use_frameworks!

platform :ios, '12.0'

target 'JLUsefulTools_Example' do

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  
  pod 'JLUsefulTools', :path => '../'
  
  target 'JLUsefulTools_Tests' do
    inherit! :search_paths
  end
  
  
end
